# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'charSettingsWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widgetCharSettings_2(object):
    def setupUi(self, widgetCharSettings_2):
        widgetCharSettings_2.setObjectName("widgetCharSettings_2")
        widgetCharSettings_2.resize(712, 402)
        self.widgetCharSettings = QtWidgets.QWidget(widgetCharSettings_2)
        self.widgetCharSettings.setGeometry(QtCore.QRect(20, 20, 581, 331))
        self.widgetCharSettings.setMinimumSize(QtCore.QSize(0, 331))
        self.widgetCharSettings.setStyleSheet("background-color: rgb(44, 52, 58);\n"
"border-radius:15px;")
        self.widgetCharSettings.setObjectName("widgetCharSettings")
        self.btnToggle_permit_read_2 = QtWidgets.QPushButton(self.widgetCharSettings)
        self.btnToggle_permit_read_2.setGeometry(QtCore.QRect(30, 90, 131, 30))
        self.btnToggle_permit_read_2.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnToggle_permit_read_2.setFont(font)
        self.btnToggle_permit_read_2.setStyleSheet("QPushButton{\n"
"text-align: center;\n"
"padding-left: 0px;\n"
"border-radius:5px;\n"
"background-color: rgb(170,200,255);\n"
"color: rgb(30, 39, 73);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"background-color: rgb(29, 42,95);\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"        color: rgb(255, 255, 255);\n"
"background-color: rgb(48, 52, 63);\n"
"}")
        self.btnToggle_permit_read_2.setCheckable(True)
        self.btnToggle_permit_read_2.setObjectName("btnToggle_permit_read_2")
        self.btnToggle_permit_read = QtWidgets.QPushButton(self.widgetCharSettings)
        self.btnToggle_permit_read.setGeometry(QtCore.QRect(30, 130, 131, 30))
        self.btnToggle_permit_read.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnToggle_permit_read.setFont(font)
        self.btnToggle_permit_read.setStyleSheet("QPushButton{\n"
"text-align: center;\n"
"padding-left: 0px;\n"
"border-radius:5px;\n"
"background-color: rgb(170,200,255);\n"
"color: rgb(30, 39, 73);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"background-color: rgb(29, 42,95);\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"        color: rgb(255, 255, 255);\n"
"background-color: rgb(48, 52, 63);\n"
"}")
        self.btnToggle_permit_read.setCheckable(True)
        self.btnToggle_permit_read.setObjectName("btnToggle_permit_read")
        self.checkBox_2 = AnimatedToggle(self.widgetCharSettings)
        self.checkBox_2.setGeometry(QtCore.QRect(40, 30, 71, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.checkBox_2.sizePolicy().hasHeightForWidth())
        self.checkBox_2.setSizePolicy(sizePolicy)
        self.checkBox_2.setAutoFillBackground(False)
        self.checkBox_2.setStyleSheet("\n"
"QCheckBox {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(44, 52, 58);\n"
"border-radius:  5px;\n"
"padding-left: 5px;\n"
"}\n"
"")
        self.checkBox_2.setText("")
        self.checkBox_2.setIconSize(QtCore.QSize(20, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.label_9 = QtWidgets.QLabel(self.widgetCharSettings)
        self.label_9.setGeometry(QtCore.QRect(130, 30, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")

        self.retranslateUi(widgetCharSettings_2)
        QtCore.QMetaObject.connectSlotsByName(widgetCharSettings_2)

    def retranslateUi(self, widgetCharSettings_2):
        _translate = QtCore.QCoreApplication.translate
        widgetCharSettings_2.setWindowTitle(_translate("widgetCharSettings_2", "Form"))
        self.btnToggle_permit_read_2.setText(_translate("widgetCharSettings_2", "Write"))
        self.btnToggle_permit_read.setText(_translate("widgetCharSettings_2", "Read"))
        self.label_9.setText(_translate("widgetCharSettings_2", "Characteristic"))
from toggle import AnimatedToggle


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widgetCharSettings_2 = QtWidgets.QWidget()
    ui = Ui_widgetCharSettings_2()
    ui.setupUi(widgetCharSettings_2)
    widgetCharSettings_2.show()
    sys.exit(app.exec_())
