# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'serviceSettingsWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widgetService(object):
    def setupUi(self, widgetService):
        widgetService.setObjectName("widgetService")
        widgetService.resize(656, 699)
        widgetService.setStyleSheet("border: 0px solid gray;")
        self.widgetServiceSettings = QtWidgets.QWidget(widgetService)
        self.widgetServiceSettings.setGeometry(QtCore.QRect(0, 10, 651, 681))
        self.widgetServiceSettings.setMinimumSize(QtCore.QSize(0, 200))
        self.widgetServiceSettings.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"border: 1px solid gray;")
        self.widgetServiceSettings.setObjectName("widgetServiceSettings")
        self.btnToggle_permit_read_2 = QtWidgets.QPushButton(self.widgetServiceSettings)
        self.btnToggle_permit_read_2.setGeometry(QtCore.QRect(30, 110, 131, 30))
        self.btnToggle_permit_read_2.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnToggle_permit_read_2.setFont(font)
        self.btnToggle_permit_read_2.setStyleSheet("QPushButton{\n"
"text-align: center;\n"
"padding-left: 0px;\n"
"border-radius:5px;\n"
"border: 0px solid gray;\n"
"background-color: rgb(170,200,255);\n"
"color: rgb(30, 39, 73);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"background-color: rgb(29, 42,95);\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"        color: rgb(255, 255, 255);\n"
"background-color: rgb(48, 52, 63);\n"
"}")
        self.btnToggle_permit_read_2.setCheckable(True)
        self.btnToggle_permit_read_2.setObjectName("btnToggle_permit_read_2")
        self.btnToggle_permit_read = QtWidgets.QPushButton(self.widgetServiceSettings)
        self.btnToggle_permit_read.setGeometry(QtCore.QRect(30, 160, 131, 30))
        self.btnToggle_permit_read.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnToggle_permit_read.setFont(font)
        self.btnToggle_permit_read.setStyleSheet("QPushButton{\n"
"text-align: center;\n"
"padding-left: 0px;\n"
"border-radius:5px;\n"
"background-color: rgb(170,200,255);\n"
"border: 0px solid gray;\n"
"color: rgb(30, 39, 73);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"background-color: rgb(29, 42,95);\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"        color: rgb(255, 255, 255);\n"
"background-color: rgb(48, 52, 63);\n"
"}")
        self.btnToggle_permit_read.setCheckable(True)
        self.btnToggle_permit_read.setObjectName("btnToggle_permit_read")
        self.checkBox_2 = AnimatedToggle(self.widgetServiceSettings)
        self.checkBox_2.setGeometry(QtCore.QRect(30, 60, 71, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.checkBox_2.sizePolicy().hasHeightForWidth())
        self.checkBox_2.setSizePolicy(sizePolicy)
        self.checkBox_2.setAutoFillBackground(False)
        self.checkBox_2.setStyleSheet("\n"
"QCheckBox {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(44, 52, 58);\n"
"border-radius:  5px;\n"
"padding-left: 5px;\n"
"}\n"
"")
        self.checkBox_2.setText("")
        self.checkBox_2.setIconSize(QtCore.QSize(20, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.label_9 = QtWidgets.QLabel(self.widgetServiceSettings)
        self.label_9.setGeometry(QtCore.QRect(240, 90, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.lbl_service_name = QtWidgets.QLabel(self.widgetServiceSettings)
        self.lbl_service_name.setGeometry(QtCore.QRect(0, 0, 151, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbl_service_name.setFont(font)
        self.lbl_service_name.setStyleSheet("text-align: center;\n"
"padding-left: 0px;\n"
"border-radius:5px;\n"
"background-color: rgb(39, 52, 105);\n"
"    color: rgb(255, 255, 255);")
        self.lbl_service_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_service_name.setObjectName("lbl_service_name")
        self.frame = QtWidgets.QFrame(self.widgetServiceSettings)
        self.frame.setGeometry(QtCore.QRect(30, 290, 581, 361))
        self.frame.setStyleSheet("background-color: rgb(231,232,237);\n"
"border: 0px solid gray;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.serviceScrollArea = QtWidgets.QScrollArea(self.frame)
        self.serviceScrollArea.setStyleSheet("")
        self.serviceScrollArea.setWidgetResizable(True)
        self.serviceScrollArea.setObjectName("serviceScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 563, 343))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.serviceScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.serviceScrollArea)

        self.retranslateUi(widgetService)
        QtCore.QMetaObject.connectSlotsByName(widgetService)

    def retranslateUi(self, widgetService):
        _translate = QtCore.QCoreApplication.translate
        widgetService.setWindowTitle(_translate("widgetService", "Form"))
        self.btnToggle_permit_read_2.setText(_translate("widgetService", "Write"))
        self.btnToggle_permit_read.setText(_translate("widgetService", "Read"))
        self.label_9.setText(_translate("widgetService", "Characteristic"))
        self.lbl_service_name.setText(_translate("widgetService", "Service"))
from toggle import AnimatedToggle
