# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'charSettingsWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from main_app import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from modules import Console
from PyQt5 import uic

class Ui_widgetCharSettings_2(QWidget):
    myIndex=0
    interface=None
    def __init__(self, parent = None):
        QWidget.__init__(self)
    def setupUi(self, widgetCharSettings_2, count=None):
        self.myIndex=count
        widgetCharSettings_2.setObjectName("widgetCharSettings_2")
        widgetCharSettings_2.resize(712, 402)
        self.widgetCharSettings = QWidget(widgetCharSettings_2)
        self.widgetCharSettings.setObjectName(u"widgetCharSettings")
        self.widgetCharSettings.setGeometry(QRect(20, 20, 641, 331))
        self.widgetCharSettings.setMinimumSize(QSize(0, 331))
        self.widgetCharSettings.setStyleSheet(u"background-color: rgb(44, 52, 58);\n"
"border-radius:15px;")
        self.btnToggle_permit_read_2 = QPushButton(self.widgetCharSettings)
        self.btnToggle_permit_read_2.setObjectName(u"btnToggle_permit_read_2")
        self.btnToggle_permit_read_2.setGeometry(QRect(30, 80, 131, 30))
        self.btnToggle_permit_read_2.setMinimumSize(QSize(100, 30))
        font = QFont()
        font.setPointSize(11)
        self.btnToggle_permit_read_2.setFont(font)
        self.btnToggle_permit_read_2.setStyleSheet(u"QPushButton{\n"
"text-align: center;\n"
"padding-left: 0px;\n"
"border-radius:5px;\n"
"background-color: rgb(170,200,255);\n"
"color: rgb(30, 39, 73);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"background-color: rgb(29, 42,95);\n"
"	color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"	\n"
"		color: rgb(255, 255, 255);\n"
"background-color: rgb(48, 52, 63);\n"
"}")
        self.btnToggle_permit_read_2.setCheckable(True)
        self.btnToggle_permit_read = QPushButton(self.widgetCharSettings)
        self.btnToggle_permit_read.setObjectName(u"btnToggle_permit_read")
        self.btnToggle_permit_read.setGeometry(QRect(30, 120, 131, 30))
        self.btnToggle_permit_read.setMinimumSize(QSize(100, 30))
        self.btnToggle_permit_read.setFont(font)
        self.btnToggle_permit_read.setStyleSheet(u"QPushButton{\n"
"text-align: center;\n"
"padding-left: 0px;\n"
"border-radius:5px;\n"
"background-color: rgb(170,200,255);\n"
"color: rgb(30, 39, 73);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"background-color: rgb(29, 42,95);\n"
"	color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"	\n"
"		color: rgb(255, 255, 255);\n"
"background-color: rgb(48, 52, 63);\n"
"}")
        self.btnToggle_permit_read.setCheckable(True)
        self.checkBox_2 = AnimatedToggle(self.widgetCharSettings)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(40, 30, 71, 41))
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.checkBox_2.sizePolicy().hasHeightForWidth())
        self.checkBox_2.setSizePolicy(sizePolicy)
        self.checkBox_2.setAutoFillBackground(False)
        self.checkBox_2.setStyleSheet(u"\n"
"QCheckBox {\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(44, 52, 58);\n"
"border-radius:  5px;\n"
"padding-left: 5px;\n"
"}\n"
"")
        self.checkBox_2.setIconSize(QSize(20, 20))
        self.label_9 = QLabel(self.widgetCharSettings)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(130, 20, 151, 61))
        font1 = QFont()
        font1.setPointSize(14)
        self.label_9.setFont(font1)
        self.label_9.setStyleSheet(u"color: rgb(255, 255, 255);")

        self.retranslateUi(widgetCharSettings_2)

        QMetaObject.connectSlotsByName(widgetCharSettings_2)
    # setupUi


    def retranslateUi(self, widgetCharSettings_2):
        _translate = QtCore.QCoreApplication.translate
        widgetCharSettings_2.setWindowTitle(_translate("widgetCharSettings_2", "Form"))
        self.btnToggle_permit_read_2.setText(_translate("widgetCharSettings_2", "Write"))
        self.btnToggle_permit_read.setText(_translate("widgetCharSettings_2", "Read"))
        self.label_9.setText(_translate("widgetCharSettings_2", "Authenticate"))
#TODO : FIX : custom code will get deleted if UI is regenrated
        self.btnToggle_permit_read.clicked.connect(self.btn_permit_read)
    def btn_permit_read(self):
        self.interface.ui.label_5.setText(f"My index is {self.myIndex}")
    def mousePressEvent(self, event):
        self.interface.ui.label_5.setText(f"Activated widget:  {self.myIndex}")
 #-------------------------------------------------------------------------       
from toggle import AnimatedToggle


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widgetCharSettings_2 = QtWidgets.QWidget()
    ui = Ui_widgetCharSettings_2()
    ui.setupUi(widgetCharSettings_2)
    widgetCharSettings_2.show()
    sys.exit(app.exec_())
