# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BLE_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1384, 948)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(1648999, 99999))
        MainWindow.setStyleSheet("        background-color: rgb(235,245,255);\n"
"border:none;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(250, 250, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setStyleSheet("background-color: rgb(250, 250, 255);")
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.mainFrame)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 9)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sideBar = QtWidgets.QFrame(self.mainFrame)
        self.sideBar.setEnabled(True)
        self.sideBar.setMinimumSize(QtCore.QSize(208, 400))
        self.sideBar.setMaximumSize(QtCore.QSize(210, 16777215))
        self.sideBar.setStyleSheet("QFrame{\n"
"border-radius:15px;\n"
"        background-color: rgb(170,200,255);\n"
"border: 0px solid gray;\n"
"border-color: rgb(190, 190, 190);\n"
"}")
        self.sideBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sideBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sideBar.setObjectName("sideBar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sideBar)
        self.verticalLayout.setContentsMargins(0, 10, 0, 9)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnMenu = QtWidgets.QPushButton(self.sideBar)
        self.btnMenu.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btnMenu.setFont(font)
        self.btnMenu.setStyleSheet("QPushButton{\n"
"        background-color: rgb(170,200,255);\n"
"    border:none;\n"
"\n"
"        color: rgb(30, 39, 73);\n"
"\n"
"text-align: center;\n"
"padding-bottom: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(30, 39, 73);\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.btnMenu.setCheckable(False)
        self.btnMenu.setObjectName("btnMenu")
        self.verticalLayout.addWidget(self.btnMenu)
        self.line_2 = QtWidgets.QFrame(self.sideBar)
        self.line_2.setMinimumSize(QtCore.QSize(0, 1))
        self.line_2.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.btnMenuExplore = QtWidgets.QPushButton(self.sideBar)
        self.btnMenuExplore.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btnMenuExplore.setFont(font)
        self.btnMenuExplore.setStyleSheet("QPushButton{\n"
"        background-color: rgb(170,200,255);\n"
"    border:none;\n"
"\n"
"        color: rgb(30, 39, 73);\n"
"\n"
"text-align: left;\n"
"padding-left: 30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(30, 39, 73);\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.btnMenuExplore.setObjectName("btnMenuExplore")
        self.verticalLayout.addWidget(self.btnMenuExplore)
        self.btnMenuGattMaker = QtWidgets.QPushButton(self.sideBar)
        self.btnMenuGattMaker.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btnMenuGattMaker.setFont(font)
        self.btnMenuGattMaker.setStyleSheet("QPushButton{\n"
"        background-color: rgb(170,200,255);\n"
"    border:none;\n"
"\n"
"        color: rgb(30, 39, 73);\n"
"\n"
"text-align: left;\n"
"padding-left: 30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(30, 39, 73);\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.btnMenuGattMaker.setObjectName("btnMenuGattMaker")
        self.verticalLayout.addWidget(self.btnMenuGattMaker)
        self.btnMenuClient = QtWidgets.QPushButton(self.sideBar)
        self.btnMenuClient.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btnMenuClient.setFont(font)
        self.btnMenuClient.setStyleSheet("QPushButton{\n"
"        background-color: rgb(170,200,255);\n"
"    border:none;\n"
"\n"
"        color: rgb(30, 39, 73);\n"
"\n"
"text-align: left;\n"
"padding-left: 30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(30, 39, 73);\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.btnMenuClient.setObjectName("btnMenuClient")
        self.verticalLayout.addWidget(self.btnMenuClient)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.frm_otas = QtWidgets.QFrame(self.sideBar)
        self.frm_otas.setMinimumSize(QtCore.QSize(0, 200))
        self.frm_otas.setStyleSheet("")
        self.frm_otas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_otas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_otas.setObjectName("frm_otas")
        self.btnOtaUpdate = QtWidgets.QPushButton(self.frm_otas)
        self.btnOtaUpdate.setGeometry(QtCore.QRect(40, 110, 131, 30))
        self.btnOtaUpdate.setMinimumSize(QtCore.QSize(100, 30))
        self.btnOtaUpdate.setStyleSheet("QPushButton{\n"
"text-align: center;\n"
"padding-left: 0px;\n"
"border-radius:5px;\n"
"background-color: rgb(39, 52, 105);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"background-color: rgb(29, 42,95);\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"        color: rgb(255, 255, 255);\n"
"background-color: rgb(48, 52, 63);\n"
"}")
        self.btnOtaUpdate.setObjectName("btnOtaUpdate")
        self.label = QtWidgets.QLabel(self.frm_otas)
        self.label.setGeometry(QtCore.QRect(40, 20, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(30, 39, 73);\n"
"")
        self.label.setObjectName("label")
        self.line_3 = QtWidgets.QFrame(self.frm_otas)
        self.line_3.setGeometry(QtCore.QRect(0, 10, 208, 1))
        self.line_3.setMinimumSize(QtCore.QSize(0, 1))
        self.line_3.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.btnFindBin = QtWidgets.QPushButton(self.frm_otas)
        self.btnFindBin.setGeometry(QtCore.QRect(40, 70, 131, 30))
        self.btnFindBin.setMinimumSize(QtCore.QSize(100, 30))
        self.btnFindBin.setStyleSheet("QPushButton{\n"
"text-align: center;\n"
"padding-left: 0px;\n"
"border-radius:5px;\n"
"background-color: rgb(39, 52, 105);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"background-color: rgb(29, 42,95);\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"        color: rgb(255, 255, 255);\n"
"background-color: rgb(48, 52, 63);\n"
"}")
        self.btnFindBin.setObjectName("btnFindBin")
        self.verticalLayout.addWidget(self.frm_otas)
        self.frame_3 = QtWidgets.QFrame(self.sideBar)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 210))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 999999))
        self.frame_3.setStyleSheet("border: 0px solid gray;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.line = QtWidgets.QFrame(self.frame_3)
        self.line.setGeometry(QtCore.QRect(0, 100, 206, 1))
        self.line.setMinimumSize(QtCore.QSize(0, 1))
        self.line.setMaximumSize(QtCore.QSize(16777215, 1))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.line.setFont(font)
        self.line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.btnauthor = QtWidgets.QPushButton(self.frame_3)
        self.btnauthor.setGeometry(QtCore.QRect(30, 110, 191, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnauthor.setFont(font)
        self.btnauthor.setStyleSheet("text-align: left;\n"
"padding-left: 0px;\n"
"color: rgb(30, 39, 73);\n"
"        background-color: rgb(170,200,255);")
        self.btnauthor.setObjectName("btnauthor")
        self.btnRepo = QtWidgets.QPushButton(self.frame_3)
        self.btnRepo.setGeometry(QtCore.QRect(20, 160, 161, 30))
        self.btnRepo.setMinimumSize(QtCore.QSize(0, 30))
        self.btnRepo.setStyleSheet("QPushButton{\n"
"text-align: center;\n"
"padding-left: 0px;\n"
"border-radius:5px;\n"
"background-color: rgb(39, 52, 105);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"background-color: rgb(29, 42,95);\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"        color: rgb(255, 255, 255);\n"
"background-color: rgb(48, 52, 63);\n"
"}")
        self.btnRepo.setObjectName("btnRepo")
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout_3.addWidget(self.sideBar)
        self.frame_5 = QtWidgets.QFrame(self.mainFrame)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_5.setStyleSheet("background-color: rgb(250, 250, 255);\n"
"border-radius:15px;\n"
"border: 0px solid gray;\n"
"border-color: rgb(190, 190, 190);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.stackedWidget = SlidingStackedWidget(self.frame_5)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget.setMouseTracking(True)
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setStyleSheet("border: 0px solid gray;")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_Gatt_Maker = QtWidgets.QWidget()
        self.page_Gatt_Maker.setObjectName("page_Gatt_Maker")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.page_Gatt_Maker)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.mainframe_gatt = QtWidgets.QFrame(self.page_Gatt_Maker)
        self.mainframe_gatt.setMinimumSize(QtCore.QSize(0, 400))
        self.mainframe_gatt.setMaximumSize(QtCore.QSize(1812, 2000))
        self.mainframe_gatt.setStyleSheet("background-color: rgb(19, 19, 19);\n"
"border-radius:15px;")
        self.mainframe_gatt.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainframe_gatt.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainframe_gatt.setObjectName("mainframe_gatt")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.mainframe_gatt)
        self.verticalLayout_3.setContentsMargins(20, 0, 40, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_9.addWidget(self.mainframe_gatt)
        self.stackedWidget.addWidget(self.page_Gatt_Maker)
        self.page_BLE_Client = QtWidgets.QWidget()
        self.page_BLE_Client.setObjectName("page_BLE_Client")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.page_BLE_Client)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.mainframe_client = QtWidgets.QFrame(self.page_BLE_Client)
        self.mainframe_client.setMinimumSize(QtCore.QSize(0, 400))
        self.mainframe_client.setMaximumSize(QtCore.QSize(1812, 2000))
        self.mainframe_client.setStyleSheet("background-color: rgb(19, 19, 19);\n"
"border-radius:15px;")
        self.mainframe_client.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainframe_client.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainframe_client.setObjectName("mainframe_client")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.mainframe_client)
        self.verticalLayout_4.setContentsMargins(20, 0, 40, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7.addWidget(self.mainframe_client)
        self.stackedWidget.addWidget(self.page_BLE_Client)
        self.page_Explore = QtWidgets.QWidget()
        self.page_Explore.setMinimumSize(QtCore.QSize(0, 0))
        self.page_Explore.setStyleSheet("")
        self.page_Explore.setObjectName("page_Explore")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_Explore)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.mainframe_explore = QtWidgets.QFrame(self.page_Explore)
        self.mainframe_explore.setMinimumSize(QtCore.QSize(0, 400))
        self.mainframe_explore.setMaximumSize(QtCore.QSize(1812, 2000))
        self.mainframe_explore.setStyleSheet("\n"
"border-radius:5px;\n"
"border: 0px solid gray;\n"
"border-color: rgb(230, 230, 230);")
        self.mainframe_explore.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainframe_explore.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainframe_explore.setObjectName("mainframe_explore")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainframe_explore)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.appFrame_2 = QtWidgets.QFrame(self.mainframe_explore)
        self.appFrame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.appFrame_2.setMaximumSize(QtCore.QSize(1000000, 100000))
        self.appFrame_2.setStyleSheet("background-color: rgb(250, 250, 255);\n"
"border-radius:5px;\n"
"border-color: rgb(85, 85, 85);\n"
"border: 0px solid gray;")
        self.appFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.appFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.appFrame_2.setObjectName("appFrame_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.appFrame_2)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_13 = QtWidgets.QFrame(self.appFrame_2)
        self.frame_13.setStyleSheet("border: 1px solid gray;\n"
"border-color: rgb(190, 190, 190);")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.scaneSliderFrame_2 = QtWidgets.QFrame(self.frame_13)
        self.scaneSliderFrame_2.setStyleSheet("border:none;")
        self.scaneSliderFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scaneSliderFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scaneSliderFrame_2.setObjectName("scaneSliderFrame_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scaneSliderFrame_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_10 = QtWidgets.QLabel(self.scaneSliderFrame_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("\n"
"color: rgb(28, 28, 28);")
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 0, 0, 1, 1)
        self.timeoutLabel_2 = QtWidgets.QLabel(self.scaneSliderFrame_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.timeoutLabel_2.setFont(font)
        self.timeoutLabel_2.setStyleSheet("\n"
"color: rgb(28, 28, 28);")
        self.timeoutLabel_2.setObjectName("timeoutLabel_2")
        self.gridLayout_5.addWidget(self.timeoutLabel_2, 0, 1, 1, 1)
        self.timeoutSlider_2 = QtWidgets.QSlider(self.scaneSliderFrame_2)
        self.timeoutSlider_2.setStyleSheet("")
        self.timeoutSlider_2.setMaximum(30)
        self.timeoutSlider_2.setPageStep(1)
        self.timeoutSlider_2.setProperty("value", 5)
        self.timeoutSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.timeoutSlider_2.setObjectName("timeoutSlider_2")
        self.gridLayout_5.addWidget(self.timeoutSlider_2, 1, 0, 1, 3)
        self.verticalLayout_8.addWidget(self.scaneSliderFrame_2)
        self.btnScan = QtWidgets.QPushButton(self.frame_13)
        self.btnScan.setMinimumSize(QtCore.QSize(0, 30))
        self.btnScan.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnScan.setFont(font)
        self.btnScan.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"        background-color: rgb(170,200,255);\n"
"    border:none;\n"
"border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(28, 28, 28);\n"
"        background-color: rgb(140,170,255);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"        color: rgb(28, 28, 28);\n"
"    background-color: rgb(110,140,255);\n"
"}")
        self.btnScan.setObjectName("btnScan")
        self.verticalLayout_8.addWidget(self.btnScan)
        self.frame_6 = QtWidgets.QFrame(self.frame_13)
        self.frame_6.setStyleSheet("border: 0px solid gray;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.timeoutSlider_3 = QtWidgets.QSlider(self.frame_6)
        self.timeoutSlider_3.setStyleSheet("")
        self.timeoutSlider_3.setMaximum(30)
        self.timeoutSlider_3.setPageStep(1)
        self.timeoutSlider_3.setProperty("value", 5)
        self.timeoutSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.timeoutSlider_3.setObjectName("timeoutSlider_3")
        self.gridLayout_6.addWidget(self.timeoutSlider_3, 1, 0, 1, 3)
        self.checkBox = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox.setStyleSheet("color: rgb(28, 28, 28);\n"
"\n"
"\n"
"QCheckBox {\n"
"   \n"
"    color:                  white;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width:                  10px;\n"
"    height:                 10px;\n"
"    border-radius:          5px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:       blue;\n"
"\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color:       gray;\n"
"\n"
"}")
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_6.addWidget(self.checkBox, 3, 0, 1, 1)
        self.btnConnect = QtWidgets.QPushButton(self.frame_6)
        self.btnConnect.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnConnect.setFont(font)
        self.btnConnect.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"        background-color: rgb(170,200,255);\n"
"    border:none;\n"
"border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(28, 28, 28);\n"
"        background-color: rgb(140,170,255);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"        color: rgb(28, 28, 28);\n"
"    background-color: rgb(110,140,255);\n"
"}")
        self.btnConnect.setObjectName("btnConnect")
        self.gridLayout_6.addWidget(self.btnConnect, 3, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setStyleSheet("color: rgb(28, 28, 28);")
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 0, 0, 1, 1)
        self.lblConnectionTime = QtWidgets.QLabel(self.frame_6)
        self.lblConnectionTime.setStyleSheet("color: rgb(28, 28, 28);")
        self.lblConnectionTime.setObjectName("lblConnectionTime")
        self.gridLayout_6.addWidget(self.lblConnectionTime, 0, 1, 1, 2)
        self.verticalLayout_8.addWidget(self.frame_6)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.horizontalLayout_8.addWidget(self.frame_13)
        self.frame_11 = QtWidgets.QFrame(self.appFrame_2)
        self.frame_11.setStyleSheet("border-color: rgb(245,245, 245);\n"
"border-radius:5px;\n"
"border: 0px solid gray;\n"
"color: rgb(45, 45, 45);\n"
"border: 0px solid gray;\n"
"border-color: rgb(190, 190, 190);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_23 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(30, 39, 73);\n"
"border: 0px solid gray;\n"
"")
        self.label_23.setObjectName("label_23")
        self.verticalLayout_5.addWidget(self.label_23)
        self.label_6 = QtWidgets.QLabel(self.frame_11)
        self.label_6.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(250, 250, 255);\n"
"border-radius:10px;\n"
"background-color: rgb(39, 52, 105);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.list_discoveredDevices = QtWidgets.QListWidget(self.frame_11)
        self.list_discoveredDevices.setMinimumSize(QtCore.QSize(0, 0))
        self.list_discoveredDevices.setMaximumSize(QtCore.QSize(10000, 1000))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.list_discoveredDevices.setFont(font)
        self.list_discoveredDevices.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border-radius:10px;\n"
"background-color: rgb(235, 245, 255);\n"
"color: rgb(45, 45, 45);\n"
"border: 1px solid gray;\n"
"border-color: rgb(190, 190, 190);")
        self.list_discoveredDevices.setModelColumn(0)
        self.list_discoveredDevices.setObjectName("list_discoveredDevices")
        self.verticalLayout_5.addWidget(self.list_discoveredDevices)
        self.horizontalLayout_8.addWidget(self.frame_11)
        self.frame_9 = QtWidgets.QFrame(self.appFrame_2)
        self.frame_9.setStyleSheet("\n"
"border-radius:10px;\n"
"border: 0px solid gray;\n"
"border-color: rgb(245,245, 245);\n"
"border: 0px solid gray;\n"
"border-color: rgb(190, 190, 190);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_22 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(30, 39, 73);\n"
"border: 0px solid gray;\n"
"border-color: rgb(190, 190, 190);")
        self.label_22.setObjectName("label_22")
        self.verticalLayout_6.addWidget(self.label_22)
        self.servicesTreeWidget = QtWidgets.QTreeWidget(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.servicesTreeWidget.setFont(font)
        self.servicesTreeWidget.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"padding-top: 20px;\n"
"border-radius:5px;\n"
"background-color: rgb(235, 245, 255);\n"
"color: rgb(45, 45, 45);\n"
"border: 1px solid gray;\n"
"border-color: rgb(190, 190, 190);")
        self.servicesTreeWidget.setAlternatingRowColors(False)
        self.servicesTreeWidget.setAnimated(True)
        self.servicesTreeWidget.setWordWrap(True)
        self.servicesTreeWidget.setObjectName("servicesTreeWidget")
        self.servicesTreeWidget.headerItem().setText(0, "1")
        self.servicesTreeWidget.header().setVisible(False)
        self.verticalLayout_6.addWidget(self.servicesTreeWidget)
        self.horizontalLayout_8.addWidget(self.frame_9)
        self.horizontalLayout_8.setStretch(0, 2)
        self.horizontalLayout_8.setStretch(1, 3)
        self.horizontalLayout_8.setStretch(2, 4)
        self.verticalLayout_2.addWidget(self.appFrame_2)
        self.frame_2 = QtWidgets.QFrame(self.mainframe_explore)
        self.frame_2.setStyleSheet("\n"
"border-radius:5px;\n"
"background-color: rgb(250, 250, 255);\n"
"\n"
"border: 0px solid gray;\n"
"border-color: rgb(190, 190, 190);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_10 = QtWidgets.QFrame(self.frame_2)
        self.frame_10.setStyleSheet("\n"
"border-radius:5px;\n"
"\n"
"\n"
"border: 1px solid gray;\n"
"border-color: rgb(190, 190, 190);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_4.setContentsMargins(10, 1, 10, 10)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_14 = QtWidgets.QFrame(self.frame_10)
        self.frame_14.setStyleSheet("border: 0px solid gray;\n"
"border-color: rgb(190, 190, 190);")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.btnLabelUUID = QtWidgets.QPushButton(self.frame_14)
        self.btnLabelUUID.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnLabelUUID.setFont(font)
        self.btnLabelUUID.setStyleSheet("text-align: left;\n"
"color: rgb(28, 28, 28);")
        self.btnLabelUUID.setObjectName("btnLabelUUID")
        self.gridLayout.addWidget(self.btnLabelUUID, 3, 1, 1, 1)
        self.btnLabelType = QtWidgets.QPushButton(self.frame_14)
        self.btnLabelType.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnLabelType.setFont(font)
        self.btnLabelType.setStyleSheet("text-align: left;\n"
"color: rgb(28, 28, 28);\n"
"padding-top: 0px;\n"
"")
        self.btnLabelType.setObjectName("btnLabelType")
        self.gridLayout.addWidget(self.btnLabelType, 7, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(28, 28, 28);")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 8, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.frame_14)
        self.frame.setStyleSheet("border: 0px solid gray;\n"
"border-color: rgb(190, 190, 190);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.text_writeChar = QtWidgets.QTextEdit(self.frame)
        self.text_writeChar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.text_writeChar.setStyleSheet("background-color: rgb(250, 250, 255);\n"
"color: rgb(45, 45, 45);\n"
"border: 1px solid gray;\n"
"border-color: rgb(190, 190, 190);")
        self.text_writeChar.setObjectName("text_writeChar")
        self.horizontalLayout.addWidget(self.text_writeChar)
        self.btnWriteChar = QtWidgets.QPushButton(self.frame)
        self.btnWriteChar.setMinimumSize(QtCore.QSize(0, 30))
        self.btnWriteChar.setMaximumSize(QtCore.QSize(4444, 16777215))
        self.btnWriteChar.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"        background-color: rgb(170,200,255);\n"
"    border:none;\n"
"border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(28, 28, 28);\n"
"        background-color: rgb(140,170,255);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"        color: rgb(28, 28, 28);\n"
"    background-color: rgb(110,140,255);\n"
"}")
        self.btnWriteChar.setObjectName("btnWriteChar")
        self.horizontalLayout.addWidget(self.btnWriteChar)
        self.btnNotify = QtWidgets.QPushButton(self.frame)
        self.btnNotify.setMinimumSize(QtCore.QSize(0, 30))
        self.btnNotify.setMaximumSize(QtCore.QSize(12222, 16777215))
        self.btnNotify.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"        background-color: rgb(170,200,255);\n"
"    border:none;\n"
"border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(28, 28, 28);\n"
"        background-color: rgb(140,170,255);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"        color: rgb(28, 28, 28);\n"
"    background-color: rgb(110,140,255);\n"
"}")
        self.btnNotify.setObjectName("btnNotify")
        self.horizontalLayout.addWidget(self.btnNotify)
        self.btnReadChar = QtWidgets.QPushButton(self.frame)
        self.btnReadChar.setMinimumSize(QtCore.QSize(0, 30))
        self.btnReadChar.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.btnReadChar.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"        background-color: rgb(170,200,255);\n"
"    border:none;\n"
"border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(28, 28, 28);\n"
"        background-color: rgb(140,170,255);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"        color: rgb(28, 28, 28);\n"
"    background-color: rgb(110,140,255);\n"
"}")
        self.btnReadChar.setObjectName("btnReadChar")
        self.horizontalLayout.addWidget(self.btnReadChar)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.gridLayout.addWidget(self.frame, 10, 0, 1, 2)
        self.label_17 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(28, 28, 28);")
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 9, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(28, 28, 28);")
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 7, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(28, 28, 28);")
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 6, 0, 1, 1)
        self.btnLabelHandle = QtWidgets.QPushButton(self.frame_14)
        self.btnLabelHandle.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnLabelHandle.setFont(font)
        self.btnLabelHandle.setStyleSheet("text-align: left;\n"
"color: rgb(28, 28, 28);")
        self.btnLabelHandle.setObjectName("btnLabelHandle")
        self.gridLayout.addWidget(self.btnLabelHandle, 6, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(28, 28, 28);")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.btnLabelPermissions = QtWidgets.QPushButton(self.frame_14)
        self.btnLabelPermissions.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnLabelPermissions.setFont(font)
        self.btnLabelPermissions.setStyleSheet("text-align: left;\n"
"color: rgb(28, 28, 28);")
        self.btnLabelPermissions.setObjectName("btnLabelPermissions")
        self.gridLayout.addWidget(self.btnLabelPermissions, 8, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(28, 28, 28);")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.btnLabelValue = QtWidgets.QPushButton(self.frame_14)
        self.btnLabelValue.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnLabelValue.setFont(font)
        self.btnLabelValue.setStyleSheet("text-align: left;\n"
"color: rgb(28, 28, 28);")
        self.btnLabelValue.setObjectName("btnLabelValue")
        self.gridLayout.addWidget(self.btnLabelValue, 9, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_14)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(30, 39, 73);\n"
"border: 0px solid gray;")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.btnLabelUUID_name = QtWidgets.QPushButton(self.frame_14)
        self.btnLabelUUID_name.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnLabelUUID_name.setFont(font)
        self.btnLabelUUID_name.setStyleSheet("text-align: left;\n"
"color: rgb(28, 28, 28);")
        self.btnLabelUUID_name.setObjectName("btnLabelUUID_name")
        self.gridLayout.addWidget(self.btnLabelUUID_name, 2, 1, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.horizontalLayout_4.addWidget(self.frame_14)
        self.horizontalLayout_4.setStretch(0, 4)
        self.horizontalLayout_2.addWidget(self.frame_10)
        self.frame_8 = QtWidgets.QFrame(self.frame_2)
        self.frame_8.setStyleSheet("\n"
"border-radius:5px;\n"
"\n"
"border: 1px solid gray;\n"
"border-color: rgb(190, 190, 190);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_10.setContentsMargins(10, 1, 10, 10)
        self.horizontalLayout_10.setSpacing(10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_12 = QtWidgets.QFrame(self.frame_8)
        self.frame_12.setStyleSheet("background-color: rgb(250, 250, 255);\n"
"border: 0px solid gray;\n"
"border-color: rgb(190, 190, 190);")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnNotifyRemove = QtWidgets.QPushButton(self.frame_12)
        self.btnNotifyRemove.setEnabled(True)
        self.btnNotifyRemove.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.btnNotifyRemove.setFont(font)
        self.btnNotifyRemove.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"        background-color: rgb(170,200,255);\n"
"    border:none;\n"
"border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(28, 28, 28);\n"
"        background-color: rgb(140,170,255);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"        color: rgb(28, 28, 28);\n"
"    background-color: rgb(110,140,255);\n"
"}")
        self.btnNotifyRemove.setCheckable(False)
        self.btnNotifyRemove.setChecked(False)
        self.btnNotifyRemove.setObjectName("btnNotifyRemove")
        self.gridLayout_2.addWidget(self.btnNotifyRemove, 3, 1, 1, 1)
        self.list_EnabledNotify = QtWidgets.QListWidget(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.list_EnabledNotify.setFont(font)
        self.list_EnabledNotify.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border-radius:10px;\n"
"background-color: rgb(235, 245, 255);\n"
"/*border: 1px solid gray;*/\n"
"\n"
"color: rgb(45, 45, 45);\n"
"border: 1px solid gray;\n"
"border-color: rgb(190, 190, 190);")
        self.list_EnabledNotify.setObjectName("list_EnabledNotify")
        self.gridLayout_2.addWidget(self.list_EnabledNotify, 2, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_12)
        self.label_18.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(245,245,245);\n"
"border-radius:10px;\n"
"background-color: rgb(39, 52, 105);")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 1, 0, 1, 2)
        self.list_EnabledNotifyValue = QtWidgets.QListWidget(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.list_EnabledNotifyValue.setFont(font)
        self.list_EnabledNotifyValue.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border-radius:10px;\n"
"\n"
"/*border: 1px solid gray;*/\n"
"background-color: rgb(235, 245, 255);\n"
"color: rgb(45, 45, 45);\n"
"border: 1px solid gray;\n"
"border-color: rgb(190, 190, 190);")
        self.list_EnabledNotifyValue.setObjectName("list_EnabledNotifyValue")
        self.gridLayout_2.addWidget(self.list_EnabledNotifyValue, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(30, 39, 73);\n"
"border: 0px solid gray;")
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 2)
        self.horizontalLayout_10.addWidget(self.frame_12)
        self.frame_15 = QtWidgets.QFrame(self.frame_8)
        self.frame_15.setStyleSheet("border: 0px solid gray;\n"
"border-color: rgb(190, 190, 190);")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_15)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.list_Streaming = QtWidgets.QListWidget(self.frame_15)
        self.list_Streaming.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border-radius:5px;\n"
"background-color: rgb(235, 245, 255);\n"
"/*border: 1px solid gray;*/\n"
"\n"
"color: rgb(45, 45, 45);\n"
"border: 1px solid gray;\n"
"border-color: rgb(190, 190, 190);")
        self.list_Streaming.setObjectName("list_Streaming")
        self.gridLayout_4.addWidget(self.list_Streaming, 3, 0, 2, 2)
        self.label_20 = QtWidgets.QLabel(self.frame_15)
        self.label_20.setMinimumSize(QtCore.QSize(0, 25))
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(250, 250, 255);\n"
"border-radius:10px;\n"
"background-color: rgb(39, 52, 105);")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 2, 0, 1, 2)
        self.btnNotifyRemove_2 = QtWidgets.QPushButton(self.frame_15)
        self.btnNotifyRemove_2.setEnabled(True)
        self.btnNotifyRemove_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.btnNotifyRemove_2.setFont(font)
        self.btnNotifyRemove_2.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"        background-color: rgb(170,200,255);\n"
"    border:none;\n"
"border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(28, 28, 28);\n"
"        background-color: rgb(140,170,255);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"        color: rgb(28, 28, 28);\n"
"    background-color: rgb(110,140,255);\n"
"}")
        self.btnNotifyRemove_2.setCheckable(False)
        self.btnNotifyRemove_2.setChecked(False)
        self.btnNotifyRemove_2.setObjectName("btnNotifyRemove_2")
        self.gridLayout_4.addWidget(self.btnNotifyRemove_2, 5, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_15)
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(30, 39, 73);\n"
"border: 0px solid gray;")
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 1, 0, 1, 1)
        self.horizontalLayout_10.addWidget(self.frame_15)
        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 1)
        self.horizontalLayout_2.addWidget(self.frame_8)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_7 = QtWidgets.QFrame(self.mainframe_explore)
        self.frame_7.setStyleSheet("background-color: rgb(48, 52, 63);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_11.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_4 = QtWidgets.QFrame(self.frame_7)
        self.frame_4.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_4)
        self.tabWidget.setMinimumSize(QtCore.QSize(700, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.console = QtWidgets.QTextEdit(self.tab)
        self.console.setMinimumSize(QtCore.QSize(700, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.console.setFont(font)
        self.console.setStyleSheet("color: rgb(170,200,255);\n"
"border: 0px solid gray;")
        self.console.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.console.setUndoRedoEnabled(False)
        self.console.setReadOnly(True)
        self.console.setObjectName("console")
        self.verticalLayout_10.addWidget(self.console)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.txtSerial = QtWidgets.QTextEdit(self.tab_2)
        self.txtSerial.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtSerial.setFont(font)
        self.txtSerial.setStyleSheet("border: 0px solid gray;\n"
"color: rgb(170,200,255);")
        self.txtSerial.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtSerial.setUndoRedoEnabled(False)
        self.txtSerial.setReadOnly(True)
        self.txtSerial.setObjectName("txtSerial")
        self.horizontalLayout_12.addWidget(self.txtSerial)
        self.frame_16 = QtWidgets.QFrame(self.tab_2)
        self.frame_16.setMinimumSize(QtCore.QSize(250, 50))
        self.frame_16.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.btnSerialConnect = QtWidgets.QPushButton(self.frame_16)
        self.btnSerialConnect.setGeometry(QtCore.QRect(160, 0, 81, 30))
        self.btnSerialConnect.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"        background-color: rgb(170,200,255);\n"
"    border:none;\n"
"border-radius:5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(28, 28, 28);\n"
"        background-color: rgb(140,170,255);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"        color: rgb(28, 28, 28);\n"
"    background-color: rgb(110,140,255);\n"
"}")
        self.btnSerialConnect.setObjectName("btnSerialConnect")
        self.txtSerialPort = QtWidgets.QTextEdit(self.frame_16)
        self.txtSerialPort.setGeometry(QtCore.QRect(30, 0, 121, 31))
        self.txtSerialPort.setStyleSheet("background-color:rgb(235, 245, 255);\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid gray;\n"
"border-color: rgb(190, 190, 190);")
        self.txtSerialPort.setObjectName("txtSerialPort")
        self.horizontalLayout_12.addWidget(self.frame_16)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_7.addWidget(self.tabWidget)
        self.horizontalLayout_11.addWidget(self.frame_4)
        self.btnConnectedState = QtWidgets.QPushButton(self.frame_7)
        self.btnConnectedState.setMinimumSize(QtCore.QSize(50, 50))
        self.btnConnectedState.setStyleSheet("")
        self.btnConnectedState.setText("")
        self.btnConnectedState.setObjectName("btnConnectedState")
        self.horizontalLayout_11.addWidget(self.btnConnectedState)
        self.verticalLayout_2.addWidget(self.frame_7)
        self.verticalLayout_2.setStretch(0, 3)
        self.verticalLayout_2.setStretch(1, 3)
        self.verticalLayout_2.setStretch(2, 2)
        self.verticalLayout_9.addWidget(self.mainframe_explore)
        self.stackedWidget.addWidget(self.page_Explore)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.mainframe_x_2 = QtWidgets.QFrame(self.page)
        self.mainframe_x_2.setMinimumSize(QtCore.QSize(0, 400))
        self.mainframe_x_2.setMaximumSize(QtCore.QSize(1812, 2000))
        self.mainframe_x_2.setStyleSheet("background-color: rgb(19, 19, 19);\n"
"border-radius:15px;")
        self.mainframe_x_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainframe_x_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainframe_x_2.setObjectName("mainframe_x_2")
        self.label_2 = QtWidgets.QLabel(self.mainframe_x_2)
        self.label_2.setGeometry(QtCore.QRect(410, 340, 67, 17))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.mainframe_x_2)
        self.stackedWidget.addWidget(self.page)
        self.horizontalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_3.addWidget(self.frame_5)
        self.horizontalLayout_3.setStretch(1, 1)
        self.gridLayout_3.addWidget(self.mainFrame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(1)
        self.timeoutSlider_2.valueChanged['int'].connect(self.timeoutLabel_2.setNum) # type: ignore
        self.timeoutSlider_3.valueChanged['int'].connect(self.lblConnectionTime.setNum) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BLE Python Device Explorer"))
        self.btnMenu.setText(_translate("MainWindow", " BLE-PyDex"))
        self.btnMenuExplore.setText(_translate("MainWindow", "      Explore"))
        self.btnMenuGattMaker.setText(_translate("MainWindow", "      Gatt Maker"))
        self.btnMenuClient.setText(_translate("MainWindow", "      BLE Client "))
        self.btnOtaUpdate.setText(_translate("MainWindow", "OTA Update"))
        self.label.setText(_translate("MainWindow", "OTAS Example"))
        self.btnFindBin.setText(_translate("MainWindow", "Load FW Bin"))
        self.btnauthor.setText(_translate("MainWindow", " Edwin Amaya"))
        self.btnRepo.setText(_translate("MainWindow", "Github"))
        self.label_10.setText(_translate("MainWindow", "Scan timeout ( s ) :"))
        self.timeoutLabel_2.setText(_translate("MainWindow", "5"))
        self.btnScan.setText(_translate("MainWindow", "Scan"))
        self.checkBox.setText(_translate("MainWindow", "Forever"))
        self.btnConnect.setText(_translate("MainWindow", "Connect"))
        self.label_3.setText(_translate("MainWindow", "Connection timeout :"))
        self.lblConnectionTime.setText(_translate("MainWindow", "5"))
        self.label_23.setText(_translate("MainWindow", "Device list"))
        self.label_6.setText(_translate("MainWindow", "  Address                               Name"))
        self.label_22.setText(_translate("MainWindow", "Gatt explorer"))
        self.btnLabelUUID.setText(_translate("MainWindow", "N/A"))
        self.btnLabelType.setText(_translate("MainWindow", "N/A"))
        self.label_12.setText(_translate("MainWindow", "Permissons :"))
        self.btnWriteChar.setText(_translate("MainWindow", "Write"))
        self.btnNotify.setText(_translate("MainWindow", "Enable Notify"))
        self.btnReadChar.setText(_translate("MainWindow", "Read"))
        self.label_17.setText(_translate("MainWindow", "Value :"))
        self.label_24.setText(_translate("MainWindow", "Type :"))
        self.label_16.setText(_translate("MainWindow", "Handle :"))
        self.btnLabelHandle.setText(_translate("MainWindow", "N/A"))
        self.label_11.setText(_translate("MainWindow", "UUID :"))
        self.btnLabelPermissions.setText(_translate("MainWindow", "N/A"))
        self.label_7.setText(_translate("MainWindow", "Name :"))
        self.btnLabelValue.setText(_translate("MainWindow", "N/A"))
        self.label_8.setText(_translate("MainWindow", "Details"))
        self.btnLabelUUID_name.setText(_translate("MainWindow", "N/A"))
        self.btnNotifyRemove.setText(_translate("MainWindow", "Remove"))
        self.label_18.setText(_translate("MainWindow", "  Handle                               Value"))
        self.label_4.setText(_translate("MainWindow", "Notifications"))
        self.label_20.setText(_translate("MainWindow", "  Handle                               Value"))
        self.btnNotifyRemove_2.setText(_translate("MainWindow", "Remove"))
        self.label_19.setText(_translate("MainWindow", "Streaming"))
        self.console.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "log"))
        self.btnSerialConnect.setText(_translate("MainWindow", "Connect"))
        self.txtSerialPort.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">/dev/ttyUSB0</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "serial"))
        self.label_2.setText(_translate("MainWindow", "intro page"))
from slidingstackedwidget import SlidingStackedWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
