# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BLE_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1550, 815)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(1900, 1019))
        MainWindow.setStyleSheet("background-color: rgb(28, 28, 28);\n"
"border:none;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(0, -1, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setStyleSheet("")
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.mainFrame)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_3.setContentsMargins(5, 0, 0, 9)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sideBar = QtWidgets.QFrame(self.mainFrame)
        self.sideBar.setEnabled(True)
        self.sideBar.setMinimumSize(QtCore.QSize(0, 0))
        self.sideBar.setMaximumSize(QtCore.QSize(210, 16777215))
        self.sideBar.setStyleSheet("QFrame{\n"
"border-radius:15px;\n"
"\n"
"\n"
"}")
        self.sideBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sideBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sideBar.setObjectName("sideBar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sideBar)
        self.verticalLayout.setContentsMargins(0, 25, 0, 9)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnMenu = QtWidgets.QPushButton(self.sideBar)
        self.btnMenu.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnMenu.setFont(font)
        self.btnMenu.setStyleSheet("QPushButton{\n"
"    \n"
"    border:none;\n"
"color: rgb(255, 255, 255);\n"
"text-align: left;\n"
"padding-left: 30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(255, 149, 0);\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.btnMenu.setCheckable(False)
        self.btnMenu.setObjectName("btnMenu")
        self.verticalLayout.addWidget(self.btnMenu)
        self.btnMenuGattMaker = QtWidgets.QPushButton(self.sideBar)
        self.btnMenuGattMaker.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnMenuGattMaker.setFont(font)
        self.btnMenuGattMaker.setStyleSheet("QPushButton{\n"
"    \n"
"    border:none;\n"
"color: rgb(255, 255, 255);\n"
"text-align: left;\n"
"padding-left: 30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 106, 255);\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.btnMenuGattMaker.setObjectName("btnMenuGattMaker")
        self.verticalLayout.addWidget(self.btnMenuGattMaker)
        self.btnMenuClient = QtWidgets.QPushButton(self.sideBar)
        self.btnMenuClient.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnMenuClient.setFont(font)
        self.btnMenuClient.setStyleSheet("QPushButton{\n"
"    \n"
"    border:none;\n"
"color: rgb(255, 255, 255);\n"
"text-align: left;\n"
"padding-left: 30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 106, 255);\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.btnMenuClient.setObjectName("btnMenuClient")
        self.verticalLayout.addWidget(self.btnMenuClient)
        self.btnMenuExplore = QtWidgets.QPushButton(self.sideBar)
        self.btnMenuExplore.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnMenuExplore.setFont(font)
        self.btnMenuExplore.setStyleSheet("QPushButton{\n"
"    \n"
"    border:none;\n"
"color: rgb(255, 255, 255);\n"
"text-align: left;\n"
"padding-left: 30px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 106, 255);\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.btnMenuExplore.setObjectName("btnMenuExplore")
        self.verticalLayout.addWidget(self.btnMenuExplore)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.frame_3 = QtWidgets.QFrame(self.sideBar)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 210))
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.line = QtWidgets.QFrame(self.frame_3)
        self.line.setGeometry(QtCore.QRect(-10, 10, 300, 1))
        self.line.setMinimumSize(QtCore.QSize(0, 1))
        self.line.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.line.setFont(font)
        self.line.setStyleSheet("background-color: rgb(109, 109, 109);")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.btnauthor = QtWidgets.QPushButton(self.frame_3)
        self.btnauthor.setGeometry(QtCore.QRect(0, 30, 171, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnauthor.setFont(font)
        self.btnauthor.setStyleSheet("color: rgb(255, 255, 255);")
        self.btnauthor.setObjectName("btnauthor")
        self.btnRepo = QtWidgets.QPushButton(self.frame_3)
        self.btnRepo.setGeometry(QtCore.QRect(110, 170, 91, 31))
        self.btnRepo.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 19, 19);\n"
"    border:none;\n"
"border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(170, 77, 77);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"        color: rgb(255, 255, 255);\n"
"    background-color: rgb(170, 27, 27);\n"
"}")
        self.btnRepo.setObjectName("btnRepo")
        self.progressBar = QtWidgets.QProgressBar(self.frame_3)
        self.progressBar.setGeometry(QtCore.QRect(20, 150, 181, 10))
        self.progressBar.setMinimumSize(QtCore.QSize(0, 10))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("border-radius:5px;\n"
"text-align: center;\n"
"background-color: rgb(70, 70, 70);")
        self.progressBar.setProperty("value", 65)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        self.label_13.setGeometry(QtCore.QRect(20, 130, 141, 17))
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setGeometry(QtCore.QRect(160, 130, 41, 20))
        self.label_14.setStyleSheet("color: rgb(148, 193, 255);\n"
"text-align: right;")
        self.label_14.setObjectName("label_14")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(10, 160, 91, 41))
        self.frame_4.setStyleSheet("border-radius:15px;\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnYoutube = QtWidgets.QPushButton(self.frame_4)
        self.btnYoutube.setMinimumSize(QtCore.QSize(0, 30))
        self.btnYoutube.setMaximumSize(QtCore.QSize(30, 30))
        self.btnYoutube.setStyleSheet("")
        self.btnYoutube.setText("")
        self.btnYoutube.setObjectName("btnYoutube")
        self.horizontalLayout.addWidget(self.btnYoutube)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnInstagram = QtWidgets.QPushButton(self.frame_4)
        self.btnInstagram.setMinimumSize(QtCore.QSize(0, 30))
        self.btnInstagram.setMaximumSize(QtCore.QSize(30, 30))
        self.btnInstagram.setStyleSheet("")
        self.btnInstagram.setText("")
        self.btnInstagram.setObjectName("btnInstagram")
        self.horizontalLayout.addWidget(self.btnInstagram)
        self.label_15 = QtWidgets.QLabel(self.frame_3)
        self.label_15.setGeometry(QtCore.QRect(20, 110, 151, 17))
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout_3.addWidget(self.sideBar)
        self.frame_5 = QtWidgets.QFrame(self.mainFrame)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.stackedWidget = SlidingStackedWidget(self.frame_5)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget.setMouseTracking(True)
        self.stackedWidget.setStyleSheet("QStackedWidget{\n"
"background-color: rgb(19, 19, 19);\n"
"border:none;\n"
"border:radius:10px;\n"
"\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_Gatt_Maker = QtWidgets.QWidget()
        self.page_Gatt_Maker.setObjectName("page_Gatt_Maker")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.page_Gatt_Maker)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.mainframe_gatt = QtWidgets.QFrame(self.page_Gatt_Maker)
        self.mainframe_gatt.setMinimumSize(QtCore.QSize(0, 400))
        self.mainframe_gatt.setMaximumSize(QtCore.QSize(1812, 2000))
        self.mainframe_gatt.setStyleSheet("background-color: rgb(19, 19, 19);\n"
"border-radius:15px;")
        self.mainframe_gatt.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainframe_gatt.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainframe_gatt.setObjectName("mainframe_gatt")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.mainframe_gatt)
        self.verticalLayout_3.setContentsMargins(20, 0, 40, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_9.addWidget(self.mainframe_gatt)
        self.stackedWidget.addWidget(self.page_Gatt_Maker)
        self.page_BLE_Client = QtWidgets.QWidget()
        self.page_BLE_Client.setObjectName("page_BLE_Client")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.page_BLE_Client)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.mainframe_client = QtWidgets.QFrame(self.page_BLE_Client)
        self.mainframe_client.setMinimumSize(QtCore.QSize(0, 400))
        self.mainframe_client.setMaximumSize(QtCore.QSize(1812, 2000))
        self.mainframe_client.setStyleSheet("background-color: rgb(19, 19, 19);\n"
"border-radius:15px;")
        self.mainframe_client.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainframe_client.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainframe_client.setObjectName("mainframe_client")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.mainframe_client)
        self.verticalLayout_4.setContentsMargins(20, 0, 40, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7.addWidget(self.mainframe_client)
        self.stackedWidget.addWidget(self.page_BLE_Client)
        self.page_Explore = QtWidgets.QWidget()
        self.page_Explore.setMinimumSize(QtCore.QSize(0, 0))
        self.page_Explore.setStyleSheet("background-color: rgb(28, 28, 28);")
        self.page_Explore.setObjectName("page_Explore")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.page_Explore)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.mainframe_explore = QtWidgets.QFrame(self.page_Explore)
        self.mainframe_explore.setMinimumSize(QtCore.QSize(0, 400))
        self.mainframe_explore.setMaximumSize(QtCore.QSize(1812, 2000))
        self.mainframe_explore.setStyleSheet("background-color: rgb(19, 19, 19);\n"
"border-radius:10px;")
        self.mainframe_explore.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainframe_explore.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainframe_explore.setObjectName("mainframe_explore")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainframe_explore)
        self.verticalLayout_2.setContentsMargins(15, 0, 20, -1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.mainframe_explore)
        self.frame.setMinimumSize(QtCore.QSize(0, 500))
        self.frame.setMaximumSize(QtCore.QSize(1600, 16777215))
        self.frame.setStyleSheet("QFrame{\n"
"\n"
"border-radius:10px;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.servicesTreeWidget = QtWidgets.QTreeWidget(self.frame)
        self.servicesTreeWidget.setGeometry(QtCore.QRect(770, 30, 481, 341))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.servicesTreeWidget.setFont(font)
        self.servicesTreeWidget.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"padding-top: 20px;\n"
"border-radius:10px;\n"
"background-color: rgb(28, 28, 28);\n"
"color: rgb(255, 255, 255);")
        self.servicesTreeWidget.setAlternatingRowColors(False)
        self.servicesTreeWidget.setAnimated(True)
        self.servicesTreeWidget.setWordWrap(True)
        self.servicesTreeWidget.setObjectName("servicesTreeWidget")
        self.servicesTreeWidget.headerItem().setText(0, "1")
        self.servicesTreeWidget.header().setVisible(False)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 390, 531, 191))
        self.frame_2.setStyleSheet("\n"
"border-radius:10px;\n"
"background-color: rgb(28, 28, 28);\n"
"\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(20, 60, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(20, 100, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(20, 130, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.btnLabelType = QtWidgets.QPushButton(self.frame_2)
        self.btnLabelType.setGeometry(QtCore.QRect(80, 60, 411, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnLabelType.setFont(font)
        self.btnLabelType.setStyleSheet("color: rgb(255, 255, 255);")
        self.btnLabelType.setObjectName("btnLabelType")
        self.btnLabelUUID = QtWidgets.QPushButton(self.frame_2)
        self.btnLabelUUID.setGeometry(QtCore.QRect(80, 100, 401, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnLabelUUID.setFont(font)
        self.btnLabelUUID.setStyleSheet("color: rgb(255, 255, 255);")
        self.btnLabelUUID.setObjectName("btnLabelUUID")
        self.btnLabelPermissions = QtWidgets.QPushButton(self.frame_2)
        self.btnLabelPermissions.setGeometry(QtCore.QRect(130, 130, 381, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnLabelPermissions.setFont(font)
        self.btnLabelPermissions.setStyleSheet("color: rgb(255, 255, 255);")
        self.btnLabelPermissions.setObjectName("btnLabelPermissions")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.btnLabelName = QtWidgets.QPushButton(self.frame_2)
        self.btnLabelName.setGeometry(QtCore.QRect(80, 30, 411, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnLabelName.setFont(font)
        self.btnLabelName.setStyleSheet("color: rgb(255, 255, 255);")
        self.btnLabelName.setObjectName("btnLabelName")
        self.appFrame_2 = QtWidgets.QFrame(self.frame)
        self.appFrame_2.setGeometry(QtCore.QRect(10, 30, 741, 341))
        self.appFrame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.appFrame_2.setMaximumSize(QtCore.QSize(1000000, 100000))
        self.appFrame_2.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.appFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.appFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.appFrame_2.setObjectName("appFrame_2")
        self.btnExplore = QtWidgets.QPushButton(self.appFrame_2)
        self.btnExplore.setGeometry(QtCore.QRect(470, 280, 121, 30))
        self.btnExplore.setMinimumSize(QtCore.QSize(0, 30))
        self.btnExplore.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnExplore.setFont(font)
        self.btnExplore.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(180, 180, 180);\n"
"    border:none;\n"
"border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(170, 77, 77);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"        color: rgb(255, 255, 255);\n"
"    background-color: rgb(170, 27, 27);\n"
"}")
        self.btnExplore.setObjectName("btnExplore")
        self.scaneSliderFrame_2 = QtWidgets.QFrame(self.appFrame_2)
        self.scaneSliderFrame_2.setGeometry(QtCore.QRect(10, 10, 291, 51))
        self.scaneSliderFrame_2.setStyleSheet("border:none;")
        self.scaneSliderFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scaneSliderFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scaneSliderFrame_2.setObjectName("scaneSliderFrame_2")
        self.timeoutSlider_2 = QtWidgets.QSlider(self.scaneSliderFrame_2)
        self.timeoutSlider_2.setGeometry(QtCore.QRect(10, 30, 161, 20))
        self.timeoutSlider_2.setStyleSheet("")
        self.timeoutSlider_2.setMaximum(30)
        self.timeoutSlider_2.setPageStep(1)
        self.timeoutSlider_2.setProperty("value", 5)
        self.timeoutSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.timeoutSlider_2.setObjectName("timeoutSlider_2")
        self.label_10 = QtWidgets.QLabel(self.scaneSliderFrame_2)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 131, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.timeoutLabel_2 = QtWidgets.QLabel(self.scaneSliderFrame_2)
        self.timeoutLabel_2.setGeometry(QtCore.QRect(150, 10, 41, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.timeoutLabel_2.setFont(font)
        self.timeoutLabel_2.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.timeoutLabel_2.setObjectName("timeoutLabel_2")
        self.label_6 = QtWidgets.QLabel(self.appFrame_2)
        self.label_6.setGeometry(QtCore.QRect(320, 20, 401, 25))
        self.label_6.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"background-color: rgb(50, 50, 50);\n"
"    ")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.list_discover_address_2 = QtWidgets.QListWidget(self.appFrame_2)
        self.list_discover_address_2.setGeometry(QtCore.QRect(320, 21, 401, 250))
        self.list_discover_address_2.setMinimumSize(QtCore.QSize(0, 250))
        self.list_discover_address_2.setMaximumSize(QtCore.QSize(550, 1000))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.list_discover_address_2.setFont(font)
        self.list_discover_address_2.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border-radius:10px;\n"
"background-color: rgb(50, 50, 50);\n"
"color: rgb(255, 255, 255);")
        self.list_discover_address_2.setObjectName("list_discover_address_2")
        self.textEdit = QtWidgets.QTextEdit(self.appFrame_2)
        self.textEdit.setGeometry(QtCore.QRect(160, 100, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background-color: rgb(30, 30, 30);\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid gray;")
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setObjectName("textEdit")
        self.radioButton = QtWidgets.QRadioButton(self.appFrame_2)
        self.radioButton.setGeometry(QtCore.QRect(20, 90, 131, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("QRadioButton {\n"
"   \n"
"    color:                  white;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  10px;\n"
"    height:                 10px;\n"
"    border-radius:          5px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:       blue;\n"
"  \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       gray;\n"
"\n"
"}")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.appFrame_2)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 130, 131, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("QRadioButton {\n"
"   \n"
"    color:                  white;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  10px;\n"
"    height:                 10px;\n"
"    border-radius:          5px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:       blue;\n"
"\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       gray;\n"
"\n"
"}")
        self.radioButton_2.setObjectName("radioButton_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.appFrame_2)
        self.textEdit_2.setGeometry(QtCore.QRect(160, 140, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setStyleSheet("background-color: rgb(30, 30, 30);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border: 1px solid gray;")
        self.textEdit_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_2.setObjectName("textEdit_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.appFrame_2)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 60, 112, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setAutoFillBackground(False)
        self.radioButton_3.setStyleSheet("QRadioButton {\n"
"   \n"
"    color:                  white;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  10px;\n"
"    height:                 10px;\n"
"    border-radius:          5px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:       blue;\n"
" \n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       gray;\n"
" \n"
"}")
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.frame_6 = QtWidgets.QFrame(self.appFrame_2)
        self.frame_6.setGeometry(QtCore.QRect(50, 220, 261, 71))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.lblConnectionTime = QtWidgets.QLabel(self.frame_6)
        self.lblConnectionTime.setGeometry(QtCore.QRect(180, 0, 67, 17))
        self.lblConnectionTime.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblConnectionTime.setObjectName("lblConnectionTime")
        self.btnConnect = QtWidgets.QPushButton(self.appFrame_2)
        self.btnConnect.setGeometry(QtCore.QRect(600, 280, 121, 30))
        self.btnConnect.setMinimumSize(QtCore.QSize(0, 30))
        self.btnConnect.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnConnect.setFont(font)
        self.btnConnect.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(180, 180, 180);\n"
"    border:none;\n"
"border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(170, 77, 77);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"        color: rgb(255, 255, 255);\n"
"    background-color: rgb(170, 27, 27);\n"
"}")
        self.btnConnect.setObjectName("btnConnect")
        self.checkBox = QtWidgets.QCheckBox(self.appFrame_2)
        self.checkBox.setGeometry(QtCore.QRect(40, 260, 92, 21))
        self.checkBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox.setObjectName("checkBox")
        self.label_3 = QtWidgets.QLabel(self.appFrame_2)
        self.label_3.setGeometry(QtCore.QRect(40, 220, 191, 17))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.timeoutSlider_3 = QtWidgets.QSlider(self.appFrame_2)
        self.timeoutSlider_3.setGeometry(QtCore.QRect(40, 240, 261, 20))
        self.timeoutSlider_3.setStyleSheet("QSlider::handle:horizontal {\n"
"    height: 4px;\n"
"    width: 3px;\n"
"    \n"
"    background-color: rgb(72, 72,72);\n"
"    margin: 0 -2px; /* expand outside the groove */\n"
"border-radius:2px;\n"
"}\n"
"")
        self.timeoutSlider_3.setMaximum(30)
        self.timeoutSlider_3.setPageStep(1)
        self.timeoutSlider_3.setProperty("value", 5)
        self.timeoutSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.timeoutSlider_3.setObjectName("timeoutSlider_3")
        self.btnScan = QtWidgets.QPushButton(self.appFrame_2)
        self.btnScan.setGeometry(QtCore.QRect(210, 20, 81, 31))
        self.btnScan.setMinimumSize(QtCore.QSize(0, 30))
        self.btnScan.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnScan.setFont(font)
        self.btnScan.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(180, 180, 180);\n"
"    border:none;\n"
"border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(170, 77, 77);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"        color: rgb(255, 255, 255);\n"
"    background-color: rgb(170, 27, 27);\n"
"}")
        self.btnScan.setObjectName("btnScan")
        self.btnExplore.raise_()
        self.scaneSliderFrame_2.raise_()
        self.list_discover_address_2.raise_()
        self.label_6.raise_()
        self.textEdit.raise_()
        self.radioButton.raise_()
        self.radioButton_2.raise_()
        self.textEdit_2.raise_()
        self.radioButton_3.raise_()
        self.frame_6.raise_()
        self.btnConnect.raise_()
        self.checkBox.raise_()
        self.label_3.raise_()
        self.timeoutSlider_3.raise_()
        self.btnScan.raise_()
        self.lblLatestVal = QtWidgets.QLabel(self.frame)
        self.lblLatestVal.setGeometry(QtCore.QRect(590, 420, 191, 31))
        self.lblLatestVal.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblLatestVal.setObjectName("lblLatestVal")
        self.btnNotify = QtWidgets.QPushButton(self.frame)
        self.btnNotify.setGeometry(QtCore.QRect(420, 590, 121, 30))
        self.btnNotify.setMinimumSize(QtCore.QSize(0, 30))
        self.btnNotify.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btnNotify.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(180, 180, 180);\n"
"    border:none;\n"
"border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(170, 77, 77);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"        color: rgb(255, 255, 255);\n"
"    background-color: rgb(170, 27, 27);\n"
"}")
        self.btnNotify.setObjectName("btnNotify")
        self.btnReadChar = QtWidgets.QPushButton(self.frame)
        self.btnReadChar.setGeometry(QtCore.QRect(290, 590, 121, 30))
        self.btnReadChar.setMinimumSize(QtCore.QSize(0, 30))
        self.btnReadChar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btnReadChar.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(180, 180, 180);\n"
"    border:none;\n"
"border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(170, 77, 77);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"        color: rgb(255, 255, 255);\n"
"    background-color: rgb(170, 27, 27);\n"
"}")
        self.btnReadChar.setObjectName("btnReadChar")
        self.btnWriteChar = QtWidgets.QPushButton(self.frame)
        self.btnWriteChar.setGeometry(QtCore.QRect(160, 590, 121, 30))
        self.btnWriteChar.setMinimumSize(QtCore.QSize(0, 30))
        self.btnWriteChar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btnWriteChar.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(180, 180, 180);\n"
"    border:none;\n"
"border-radius:10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(170, 77, 77);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"        color: rgb(255, 255, 255);\n"
"    background-color: rgb(170, 27, 27);\n"
"}")
        self.btnWriteChar.setObjectName("btnWriteChar")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(590, 400, 67, 17))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(580, 470, 91, 17))
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.lblCharVal = QtWidgets.QLabel(self.frame)
        self.lblCharVal.setGeometry(QtCore.QRect(580, 490, 191, 17))
        self.lblCharVal.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblCharVal.setObjectName("lblCharVal")
        self.frame_2.raise_()
        self.servicesTreeWidget.raise_()
        self.appFrame_2.raise_()
        self.lblLatestVal.raise_()
        self.btnNotify.raise_()
        self.btnReadChar.raise_()
        self.btnWriteChar.raise_()
        self.label_4.raise_()
        self.label_8.raise_()
        self.lblCharVal.raise_()
        self.verticalLayout_2.addWidget(self.frame)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_5 = QtWidgets.QLabel(self.mainframe_explore)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(60)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(48, 48, 48);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_9 = QtWidgets.QLabel(self.mainframe_explore)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(90)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(89, 89, 89);\n"
"")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.mainframe_explore)
        self.textBrowser_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.textBrowser_2.setStyleSheet("border:none;")
        self.textBrowser_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.horizontalLayout_2.addWidget(self.textBrowser_2)
        self.horizontalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.setStretch(0, 1)
        self.horizontalLayout_4.addWidget(self.mainframe_explore)
        self.stackedWidget.addWidget(self.page_Explore)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.mainframe_x_2 = QtWidgets.QFrame(self.page)
        self.mainframe_x_2.setMinimumSize(QtCore.QSize(0, 400))
        self.mainframe_x_2.setMaximumSize(QtCore.QSize(1812, 2000))
        self.mainframe_x_2.setStyleSheet("background-color: rgb(19, 19, 19);\n"
"border-radius:15px;")
        self.mainframe_x_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainframe_x_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainframe_x_2.setObjectName("mainframe_x_2")
        self.label_2 = QtWidgets.QLabel(self.mainframe_x_2)
        self.label_2.setGeometry(QtCore.QRect(410, 340, 67, 17))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.mainframe_x_2)
        self.stackedWidget.addWidget(self.page)
        self.horizontalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_3.addWidget(self.frame_5)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.gridLayout_3.addWidget(self.mainFrame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.timeoutSlider_2.valueChanged['int'].connect(self.timeoutLabel_2.setNum) # type: ignore
        self.timeoutSlider_3.valueChanged['int'].connect(self.lblConnectionTime.setNum) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnMenu.setText(_translate("MainWindow", "      Pin Menu"))
        self.btnMenuGattMaker.setText(_translate("MainWindow", "      Gatt Maker"))
        self.btnMenuClient.setText(_translate("MainWindow", "      BLE Client "))
        self.btnMenuExplore.setText(_translate("MainWindow", "      Explore"))
        self.btnauthor.setText(_translate("MainWindow", "    Edwin Amaya"))
        self.btnRepo.setText(_translate("MainWindow", "Github"))
        self.label_13.setText(_translate("MainWindow", "Project completion"))
        self.label_14.setText(_translate("MainWindow", "  65%"))
        self.label_15.setText(_translate("MainWindow", "BLE Xplorer 2022"))
        self.label.setText(_translate("MainWindow", "Type  :"))
        self.label_11.setText(_translate("MainWindow", "UUID :"))
        self.label_12.setText(_translate("MainWindow", "Permissons :"))
        self.btnLabelType.setText(_translate("MainWindow", "N/A"))
        self.btnLabelUUID.setText(_translate("MainWindow", "N/A"))
        self.btnLabelPermissions.setText(_translate("MainWindow", "N/A"))
        self.label_7.setText(_translate("MainWindow", "Name :"))
        self.btnLabelName.setText(_translate("MainWindow", "N/A"))
        self.btnExplore.setText(_translate("MainWindow", "Explore"))
        self.label_10.setText(_translate("MainWindow", "Scan timeout ( s ) :"))
        self.timeoutLabel_2.setText(_translate("MainWindow", "5"))
        self.label_6.setText(_translate("MainWindow", "  Address                               Name"))
        self.radioButton.setText(_translate("MainWindow", "Scan for address :"))
        self.radioButton_2.setText(_translate("MainWindow", "Scan for address :"))
        self.radioButton_3.setText(_translate("MainWindow", "Scan for all"))
        self.lblConnectionTime.setText(_translate("MainWindow", "5"))
        self.btnConnect.setText(_translate("MainWindow", "Connect"))
        self.checkBox.setText(_translate("MainWindow", "Forever"))
        self.label_3.setText(_translate("MainWindow", "Connection duration (min):"))
        self.btnScan.setText(_translate("MainWindow", "Scan"))
        self.lblLatestVal.setText(_translate("MainWindow", "Latest val: "))
        self.btnNotify.setText(_translate("MainWindow", "Enable Notify"))
        self.btnReadChar.setText(_translate("MainWindow", "Read"))
        self.btnWriteChar.setText(_translate("MainWindow", "Write"))
        self.label_4.setText(_translate("MainWindow", "Notify:"))
        self.label_8.setText(_translate("MainWindow", "Other Char"))
        self.lblCharVal.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "Explore"))
        self.label_9.setText(_translate("MainWindow", "|"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#909090;\">Explore services and characteristics</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#909090;\">on connectable devices.</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "intro page"))
from slidingstackedwidget import SlidingStackedWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
