# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'charSettingsWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from main_app import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from modules import Console
from PyQt5 import uic

class widgetCharSettings(QWidget):
    def __init__(self, parent = None):
        QWidget.__init__(self)
        uic.loadUi(r'charSettingsWidget.ui', self)
        
        